In [10]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [11]:
df = pd.read_csv('E:/Employee-Attrition-Prediction-main/Employee-Attrition.csv')
df.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2

In [12]:
from sklearn.model_selection import train_test_split,GridSearchCV, cross_validate
from sklearn.preprocessing import StandardScaler,LabelEncoder
categories = df.select_dtypes(include=['object']).columns
for col in categories:
    df[col] = LabelEncoder().fit_transform(df[col])
X = df.drop(['Attrition'], axis=1)
y = df['Attrition']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [13]:
Y=df['Attrition']
X=df.drop(['EmployeeCount','Attrition','EmployeeNumber','Over18','StandardHours'],axis=1)

In [44]:
from sklearn.tree import DecisionTreeClassifier,plot_tree
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
clf = DecisionTreeClassifier(criterion='entropy',random_state=42,max_depth=5,min_samples_leaf =1,min_samples_split=10)
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))
cm = confusion_matrix(y_test, y_pred)

Accuracy: 0.8333333333333334
              precision    recall  f1-score   support

           0       0.88      0.94      0.91       255
           1       0.25      0.13      0.17        39

    accuracy                           0.83       294
   macro avg       0.56      0.53      0.54       294
weighted avg       0.79      0.83      0.81       294

In [49]:
from sklearn.model_selection import GridSearchCV

params = {
    'max_depth': [5, 10, 15],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 3, 5],
    'criterion': ['gini', 'entropy']
}

grid = GridSearchCV(
    DecisionTreeClassifier(class_weight='balanced'),
    param_grid=params,
    cv=5,
    scoring='recall'
)
grid.fit(X_train, y_train)
print("Best parameters found: ", grid.best_params_)
print("Best score found: ", grid.best_score_)
best_model = grid.best_estimator_
y_pred = best_model.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

Best parameters found:  {'criterion': 'entropy', 'max_depth': 5, 'min_samples_leaf': 5, 'min_samples_split': 5}
Best score found:  0.5907692307692308
Accuracy: 0.7789115646258503
              precision    recall  f1-score   support

           0       0.90      0.84      0.87       255
           1       0.27      0.38      0.32        39

    accuracy                           0.78       294
   macro avg       0.58      0.61      0.59       294
weighted avg       0.82      0.78      0.79       294